chore: load defined library files in bash

diff --git a/config/bashrc b/config/bashrc
--- a/config/bashrc
+++ b/config/bashrc
@@ -9,6 +9,21 @@ shopt -s checkwinsize # update the values of LINES and COLUMNS after each comman
 shopt -s autocd # if a command is entered that is not a path, assume it is a path and cd to it
 
 HISTFILE=$HOME/.bash_history
+export TERM=xterm-256color
+export MANPATH="/usr/local/man:$MANPATH"
+export HISTSIZE=100000
+export SAVEHIST=$HISTSIZE
+export MANPATH="/usr/local/man:$MANPATH"
+GPG_TTY=$(tty)
+export GPG_TTY
+export LANG=en_US.UTF-8
+export EDITOR=vim
+export PAGER='bat '
+export MANPAGER="sh -c 'col -bx | bat -l man -p'"
+export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins"
+arch="$(arch)"
+export ARCH="${arch}"
+
 ZSH=${ZSH:-$HOME/.oh-my-zsh}
 ZSH_CUSTOM=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}
 PS1='[\u@\h \W]\$ '
@@ -46,6 +61,18 @@ if [[ -d "$ICLOUD"/dot && -f "$ICLOUD"/dot/secrets.json ]]; then
     else
         echo "no secrets file found"
     fi
+fi
+
+# TODO: ensure library is available in bash as well
+if [[ -d "$DOT_ZLIB_DIR" ]]; then
+    for lib in "${DOT_ZLIB_DIR}"/* ; do
+        if [[ ! "${DOT_PROJECT_DEBUG}x" == "x" && "${DOT_PROJECT_DEBUG}" == true ]]; then
+            echo "loading: $lib"
+        fi
+        source "$lib" || true
+    done
+else
+    echo "Warning: DOT_ZLIB_DIR not found: $DOT_ZLIB_DIR"
 fi
 
 export ICLOUD ICLOUD_DOCUMENTS ICLOUD_DOWNLOADS ICLOUD_SCREENSHOTS
